{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "skool.fullname")) | default dict -}}
{{- $data := (get $secret "data") | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skool.fullname" . }}
  labels:
    {{- include "skool.labels" . | nindent 4 }}
spec:
  type: Opaque
data:
  {{- $cookieKey := (get $data "COOKIE_KEY") | default (randNumeric 64 | b64enc) }}
  COOKIE_KEY: {{ $cookieKey }}

  {{- $webhookKey := (get $data "WEBHOOK_KEY") | default (randNumeric 64 | b64enc) }}
  WEBHOOK_KEY: {{ $webhookKey }}
