{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "skool.fullname" .)) | default dict -}}
{{- $data := (get $secret "data") | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skool.fullname" . }}
  labels:
    {{- include "skool.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $tokenKey := (get $data "TOKEN_KEY") | default (randNumeric 64 | b64enc) }}
  TOKEN_KEY: {{ $tokenKey }}
