apiVersion: v2
name: auth1
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "0.1.2"
dependencies:
  - name: redis-cluster
    alias: redis
    version: 6.x.x
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
maintainers:
  - name: ThePicoNerd
    email: ake@amcoff.net
