apiVersion: v2
name: auth1
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: redis-cluster
    alias: redis
    version: "6.3.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis-cluster.enabled
maintainers:
  - name: ThePicoNerd
    email: ake@amcoff.net
