apiVersion: v1
kind: Secret
metadata:
  name: {{ include "schedule.fullname" . }}
  labels:
    {{- include "schedule.labels" . | nindent 4 }}
type: Opaque
data:
  jwt: {{ randAlphaNum 64 | b64enc }}
