apiVersion: v2
name: oden
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: meilisearch
    version: "0.1.18"
    repository: "https://meilisearch.github.io/meilisearch-kubernetes"
    condition: meilisearch.enabled
  - name: munin
maintainers:
  - name: ThePicoNerd
    email: ake@amcoff.net
