apiVersion: v2
name: oden
description: A Helm chart for Kubernetes
type: application
version: 0.2.7
dependencies:
  - name: meilisearch
    version: 0.1.45
    repository: "https://meilisearch.github.io/meilisearch-kubernetes"
    condition: meilisearch.enabled
  - name: munin
    version: 0.2.7
  - name: hugin
    version: 0.2.7
maintainers:
  - name: akeamc
    email: ake@amcoff.net
