name: Lint and Test Charts

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/helm/chart-testing-action/issues/65#issuecomment-729818549
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: lint
          config: ct.yaml

  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: install
          config: ct.yaml
